{"name": "test_get_task_negative", "status": "passed", "description": "Проверка получения задачи с некорректным ID", "steps": [{"name": "Попытка получить фейковую задачу через task_api.get_task", "status": "passed", "steps": [{"name": "Получить задачу по ID '34534534234'", "status": "passed", "parameters": [{"name": "task_id", "value": "'34534534234'"}], "start": 1748203198743, "stop": 1748203200490}], "start": 1748203198743, "stop": 1748203200490}], "start": 1748203198743, "stop": 1748203200491, "uuid": "4d824da0-8308-4970-a185-c77ee4e34297", "historyId": "44de99435f5a5a70aa6a7f419db40385", "testCaseId": "44de99435f5a5a70aa6a7f419db40385", "fullName": "tests.api.api_tests#test_get_task_negative", "labels": [{"name": "feature", "value": "Негативные тесты получения задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "api_tests"}, {"name": "host", "value": "PC-Andrei"}, {"name": "thread", "value": "8768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.api_tests"}]}